"""create filmes table

Revision ID: 67137af84ea1
Revises: e14510ce2187
Create Date: 2026-09-05 19:56:49.266480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67137af84ea1'
down_revision: Union[str, Sequence[str], None] = 'e14510ce2187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filmes_id'), 'filmes', ['id'], unique=False)
    op.create_index(op.f('ix_filmes_user_id'), 'filmes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filmes_user_id'), table_name='filmes')
    op.drop_index(op.f('ix_filmes_id'), table_name='filmes')
    op.drop_table('filmes')
    # ### end Alembic commands ###
