"""create livros table

Revision ID: da0910568598
Revises: 7713a0ac1624
Create Date: 2026-09-05 19:49:52.137814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0910568598'
down_revision: Union[str, Sequence[str], None] = '7713a0ac1624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livros_id'), 'livros', ['id'], unique=False)
    op.create_index(op.f('ix_livros_user_id'), 'livros', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_livros_user_id'), table_name='livros')
    op.drop_index(op.f('ix_livros_id'), table_name='livros')
    op.drop_table('livros')
    # ### end Alembic commands ###
